email = "uwu@example.org"
certs = "/var/certs" 
token_file = ""
hook = "/etc/certs/hook.sh"
http_port = 80

#[permissions]
#owner = 0
#group = 0
#file = 0o600
#folder = 0o700

#[log]
#ident = "update-certs"
#facility = "local0"

[[group]]
name = "example"
domains = [
    "example.org",
    "*.example.org",
    "baz.example.org",
]

[[group]]
name = "private"
folder = "example"
domains = [
    "priv.example.org"
]

[[group]]
name = "example_2"
email = "owo@example.org"
domains = [
    "foo.example.org",
    "bar.example.org"
]
