#!/bin/sh

/usr/local/bin/knot keys \
    -output authorized-keys \
    -internal-api "http://${KNOT_SERVER_INTERNAL_LISTEN_ADDR:-localhost:5444}" \
    -git-dir "${KNOT_REPO_SCAN_PATH:-/var/git/repositories}" \
    -log-path "/var/git/log"
